name: Sync
on:
  push:
    branches:
      - master

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request to develop
        id: pull_to_develop
        uses: tretuna/sync-branches@1.2.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "master"
          TO_BRANCH: "develop"
#       - name: Opening pull request to release
#         id: pull_to_release
#         uses: tretuna/sync-branches@1.2.0
#         with:
#           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#           FROM_BRANCH: "master"
#           TO_BRANCH: "release"
      - name: Merge PR to develop
        id: merge_to_develop
        uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.MERGE_PR }}
          merge-method: merge
          pull-request: ${{ steps.pull_to_develop.outputs.PULL_REQUEST_NUMBER }}
