name: Back Merge
on:
  push:
    branches:
      - master
      - release

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - name: 'Output Env'
        run: echo "Github base branch - ${{ steps.vars.outputs.short_ref }}"
      - name: Opening pull request to develop
        id: pull_to_develop
        if: ${{ steps.vars.outputs.short_ref }} == 'release'
        uses: tretuna/sync-branches@1.2.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "release"
          TO_BRANCH: "develop"
      - name: Opening pull request to release
        if: ${{ steps.vars.outputs.short_ref }} == 'master'
        id: pull_to_release
        uses: tretuna/sync-branches@1.2.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "master"
          TO_BRANCH: "release"
